version: "3"
services:
  nginx-react:
    container_name: portfolio-fe
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
